// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfMu38tUTC6lmDJEQiNtfcH-n2eqrZFc',
    appId: '1:971712343674:web:3ce3529c695ac2812a55c3',
    messagingSenderId: '971712343674',
    projectId: 'food-app-24d92',
    authDomain: 'food-app-24d92.firebaseapp.com',
    storageBucket: 'food-app-24d92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfGVdrAs7yrpWRGlvZwH2_ty6wd1N_kJw',
    appId: '1:971712343674:android:d586ba4bf6ae5f1d2a55c3',
    messagingSenderId: '971712343674',
    projectId: 'food-app-24d92',
    storageBucket: 'food-app-24d92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXgE-iXfVu6fkIeg-7tbbPTr7oBlhcU4U',
    appId: '1:971712343674:ios:d94f542c69eaa6232a55c3',
    messagingSenderId: '971712343674',
    projectId: 'food-app-24d92',
    storageBucket: 'food-app-24d92.firebasestorage.app',
    iosBundleId: 'io.github.toberocat.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXgE-iXfVu6fkIeg-7tbbPTr7oBlhcU4U',
    appId: '1:971712343674:ios:d94f542c69eaa6232a55c3',
    messagingSenderId: '971712343674',
    projectId: 'food-app-24d92',
    storageBucket: 'food-app-24d92.firebasestorage.app',
    iosBundleId: 'io.github.toberocat.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfMu38tUTC6lmDJEQiNtfcH-n2eqrZFc',
    appId: '1:971712343674:web:c03c7c941eca86e52a55c3',
    messagingSenderId: '971712343674',
    projectId: 'food-app-24d92',
    authDomain: 'food-app-24d92.firebaseapp.com',
    storageBucket: 'food-app-24d92.firebasestorage.app',
  );
}
